### ISSUE TITLE
Failure to copy steer files from XRootD

### ISSUE THREAD

**Issue by veprbl** [eic/detector_benchmarks#43]
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/3613730#L3651
```
[Wed Aug  7 12:06:00 2024]
rule tracking_performance_sim:
    input: EPIC/EVGEN/SINGLE/pi-/1GeV/3to50deg/pi-_1GeV_3to50deg.steer, warmup/epic_craterlake_tracking_only.edm4hep.root
    output: sim_output/tracking_performance/epic_craterlake_tracking_only/pi-/1GeV/3to50deg/pi-_1GeV_3to50deg.0000.edm4hep.root
    log: sim_output/tracking_performance/epic_craterlake_tracking_only/pi-/1GeV/3to50deg/pi-_1GeV_3to50deg.0000.edm4hep.root.log
    jobid: 16
    reason: Updated input files: EPIC/EVGEN/SINGLE/pi-/1GeV/3to50deg/pi-_1GeV_3to50deg.steer; Input files updated by another job: warmup/epic_craterlake_tracking_only.edm4hep.root
    wildcards: DETECTOR_CONFIG=epic_craterlake_tracking_only, PARTICLE=pi-, ENERGY=1GeV, PHASE_SPACE=3to50deg, INDEX=0000
    resources: tmpdir=/tmp

Waiting at most 5 seconds for missing files.
Traceback (most recent call last):
  File "/opt/local/lib/python3.10/site-packages/snakemake/__init__.py", line 760, in snakemake
    success = workflow.execute(
  File "/opt/local/lib/python3.10/site-packages/snakemake/workflow.py", line 1095, in execute
    raise e
  File "/opt/local/lib/python3.10/site-packages/snakemake/workflow.py", line 1091, in execute
    success = self.scheduler.schedule()
  File "/opt/local/lib/python3.10/site-packages/snakemake/scheduler.py", line 592, in schedule
    self.run(runjobs)
  File "/opt/local/lib/python3.10/site-packages/snakemake/scheduler.py", line 641, in run
    executor.run_jobs(
  File "/opt/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 155, in run_jobs
    self.run(
  File "/opt/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 536, in run
    future = self.run_single_job(job)
  File "/opt/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 589, in run_single_job
    self.cached_or_run, job, run_wrapper, *self.job_args_and_prepare(job)
  File "/opt/local/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 541, in job_args_and_prepare
    job.prepare()
  File "/opt/local/lib/python3.10/site-packages/snakemake/jobs.py", line 850, in prepare
    wait_for_files(self.input, latency_wait=self.dag.workflow.latency_wait)
  File "/opt/local/lib/python3.10/site-packages/snakemake/io.py", line 881, in wait_for_files
    raise IOError(
OSError: Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
EPIC/EVGEN/SINGLE/pi-/1GeV/3to50deg/pi-_1GeV_3to50deg.steer
```

Could be that XRootD is not stable and xrdcp is failing silently.

**Comment by veprbl** [comment]
This is partially addressed by https://github.com/eic/detector_benchmarks/commit/c46707edc686d08a002d01b671b797292ddad5ff#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7R125

**Comment by veprbl** [comment]
Still an issue, gives flaky failures in sim:backwards_ecal

**Comment by veprbl** [comment]
Somehow it's almost always the `EPIC/EVGEN/SINGLE/e-/20GeV/130to177deg/e-_20GeV_130to177deg.steer`.
